nodeLinker: node-modules

packageExtensions:
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  "@linaria/webpack-loader@*":
    dependencies:
      "@babel/core": "*"
      "webpack": "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "@storybook/preset-create-react-app@*":
    dependencies:
      react-refresh: "*"
      typescript: "*"
      webpack: "*"
  "@mdx-js/loader@*":
    dependencies:
      react: "*"
  "@storybook/instrumenter@*":
    dependencies:
      react: "*"
      react-dom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
